apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication
  labels:
    app: webapplication
  namespace: ibtesting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapplication
  template:
    metadata:
      labels:
        app: webapplication
    spec:
      containers:
        - name: webapplication
          image: ibtesting.azurecr.io/ibiot.com_website-main:latest
          ports:
            - containerPort: 80
