apiVersion: v1
kind: Service
metadata:
  name: webapplication
  namespace: namespace-workflow-1688103216000
spec:
  type: LoadBalancer
  selector:
    app: webapplication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
