apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibiotmain
  labels:
    app: ibiotmain
  namespace: namespace-workflow-1688114298580
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibiotmain
  template:
    metadata:
      labels:
        app: ibiotmain
    spec:
      containers:
        - name: ibiotmain
          image: acrworkflow1688114298580.azurecr.io/image-workflow-1688114298580:latest
          ports:
            - containerPort: 80