apiVersion: v1
kind: Service
metadata:
  name: webapplication
  namespace: namespace-workflow-1687866844057
spec:
  type: LoadBalancer
  selector:
    app: webapplication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80