apiVersion: v1
kind: Service
metadata:
  name: ibiotmain
  namespace: namespace-workflow-1688114298580
spec:
  type: LoadBalancer
  selector:
    app: ibiotmain
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80